apt-cacher-ng: Further progress on apt-cacher-ng configuration

diff --git a/apt-cacher-ng/Makefile b/apt-cacher-ng/Makefile
--- a/apt-cacher-ng/Makefile
+++ b/apt-cacher-ng/Makefile
@@ -61,72 +61,105 @@ endef
 
 define Package/apt-cacher-ng/install
 	$(INSTALL_DIR) $(1)/usr/sbin
-	$(INSTALL_BIN) $(PKG_BUILD_DIR)/apt-cacher-ng $(1)/usr/sbin/apt-cacher-ng
+	$(INSTALL_BIN) $(PKG_BUILD_DIR)/apt-cacher-ng $(1)/usr/sbin/
 	$(INSTALL_DIR) $(1)/etc/apt-cacher-ng
-	$(INSTALL_CONF) $(PKG_BUILD_DIR)/conf/acng.conf $(1)/etc/apt-cacher-ng/acng.conf
-	$(INSTALL_CONF) $(PKG_BUILD_DIR)/conf/security.conf $(1)/etc/apt-cacher-ng/security.conf
+	$(INSTALL_CONF) $(PKG_BUILD_DIR)/conf/acng.conf $(1)/etc/apt-cacher-ng/
+	$(INSTALL_CONF) $(PKG_BUILD_DIR)/conf/security.conf $(1)/etc/apt-cacher-ng/
+	$(INSTALL_CONF) files/backends_debian $(1)/etc/apt-cacher-ng/
+	$(INSTALL_CONF) files/backends_debian.default $(1)/etc/apt-cacher-ng/
+	$(INSTALL_CONF) files/backends_debvol $(1)/etc/apt-cacher-ng/
+	$(INSTALL_CONF) files/backends_ubuntu $(1)/etc/apt-cacher-ng/
+	$(INSTALL_CONF) files/backends_ubuntu.default $(1)/etc/apt-cacher-ng/
+	$(INSTALL_DIR) $(1)/etc/init.d/
+	$(INSTALL_BIN) files/apt-cacher-ng.init $(1)/etc/init.d/apt-cacher-ng
 	$(INSTALL_DIR) $(1)/usr/lib/apt-cacher-ng
-	$(CP) $(PKG_BUILD_DIR)/conf/archlx_mirrors $(1)/usr/lib/apt-cacher-ng/archlx_mirrors
-	$(CP) $(PKG_BUILD_DIR)/conf/cygwin_mirrors $(1)/usr/lib/apt-cacher-ng/cygwin_mirrors
-	$(CP) $(PKG_BUILD_DIR)/conf/deb_mirrors.gz $(1)/usr/lib/apt-cacher-ng/deb_mirrors.gz
-	$(CP) $(PKG_BUILD_DIR)/conf/debvol_mirrors.gz $(1)/usr/lib/apt-cacher-ng/debvol_mirrors.gz
-	$(CP) $(PKG_BUILD_DIR)/conf/delconfirm.html $(1)/usr/lib/apt-cacher-ng/delconfirm.html
-	$(CP) $(PKG_BUILD_DIR)/distkill.pk $(1)/usr/lib/apt-cacher-ng/distkill.pl
-	$(CP) $(PKG_BUILD_DIR)/conf/epel_mirrors $(1)/usr/lib/apt-cacher-ng/epel_mirrors
-	$(CP) $(PKG_BUILD_DIR)/expire-caller.pl $(1)/usr/lib/apt-cacher-ng/expire-caller.pl
-	$(CP) $(PKG_BUILD_DIR)/conf/fedora_mirrors $(1)/usr/lib/apt-cacher-ng/fedora_mirrors
-	$(INSTALL_BIN) $(PKG_BUILD_DIR)/in.acng $(1)/usr/lib/apt-cacher-ng/in.acng
-	$(CP) $(PKG_BUILD_DIR)/conf/maint.html $(1)/usr/lib/apt-cacher-ng/maint.html
-	$(CP) $(PKG_BUILD_DIR)/conf/report.html $(1)/usr/lib/apt-cacher-ng/report.html
-	$(CP) $(PKG_BUILD_DIR)/conf/sfnet_mirrors $(1)/usr/lib/apt-cacher-ng/sfnet_mirrors
-	$(CP) $(PKG_BUILD_DIR)/conf/sl_mirrors $(1)/usr/lib/apt-cacher-ng/sl_mirrors
-	$(CP) $(PKG_BUILD_DIR)/conf/style.css $(1)/usr/lib/apt-cacher-ng/style.css
-	$(CP) $(PKG_BUILD_DIR)/conf/ubuntu_mirrors $(1)/usr/lib/apt-cacher-ng/ubuntu_mirrors
-	$(CP) $(PKG_BUILD_DIR)/urlencode-fixer.pl $(1)/usr/lib/apt-cacher-ng/urlencode-fixer.pl
-	$(CP) $(PKG_BUILD_DIR)/conf/userinfo.html $(1)/usr/lib/apt-cacher-ng/userinfo.html
+	$(CP) $(PKG_BUILD_DIR)/conf/archlx_mirrors $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/cygwin_mirrors $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/deb_mirrors.gz $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/debvol_mirrors.gz $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/delconfirm.html $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/distkill.pl $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/epel_mirrors $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/expire-caller.pl $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/fedora_mirrors $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/maint.html $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/report.html $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/sfnet_mirrors $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/sl_mirrors $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/style.css $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/ubuntu_mirrors $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/urlencode-fixer.pl $(1)/usr/lib/apt-cacher-ng/
+	$(CP) $(PKG_BUILD_DIR)/conf/userinfo.html $(1)/usr/lib/apt-cacher-ng/
 endef
 
 define Package/apt-cacher-ng/conffiles
 /etc/apt-cacher-ng/acng.conf
 /etc/apt-cacher-ng/security.conf
+/etc/apt-cacher-ng/backends_debian
+/etc/apt-cacher-ng/backends_debian.default
+/etc/apt-cacher-ng/backends_debvol
+/etc/apt-cacher-ng/backends_ubuntu
+/etc/apt-cacher-ng/backends_ubuntu.default
 endef
 
 define Package/apt-cacher-ng/postinst
 #!/bin/sh
+if [ ! -e "/etc/apt-cacher-ng/.configured" ]; then
 
-    # ADDUSER "apt-cacher-ng" --quiet --system --group --no-create-home --home /var/cache/apt-cacher-ng
+	# ADDUSER "apt-cacher-ng" --system --group --no-create-home --home /var/cache/apt-cacher-ng
+	echo -e "\033[1m* Adding 'apt-cacher-ng' user and group...\033[0m"
 
-    ## This may be moved to the init script, for the fact that /var/ is currently a volatile directory
-    ## Perhaps we can add a way to detect if /var/ is volatile or not?
-    ## Also, $CDIR may need moved to non-volatile storage?
-    # CDIR=/var/cache/apt-cacher-ng
-    # LDIR=/var/log/apt-cacher-ng
-    # for x in $CDIR $LDIR ; do
-    #   if [ ! -d "$x" ]; then
-    #     mkdir -p "$x"
-    #     chown apt-cacher-ng:apt-cacher-ng "$x"
-    #     chmod 2755 "$x"
-    #   fi
-    # done
+	# check for a free UID in the system user range (500-1000)
+	for UID in $$(seq 500 1000)
+	do
+		grep -q -e "^[^:]*:[^:]:$$UID:" /etc/passwd || break
+	done
+	[ $$UID -eq 1000 ] && { echo "ERROR: Could not find a suitable UID"; exit 1; }
 
-    # perhaps we should test for ownership and file mode (apt-cacher-ng:apt-cacher-ng; 0600)
-    chown apt-cacher-ng:apt-cacher-ng /etc/apt-cacher-ng/security.conf
-    chmod 0600 /etc/apt-cacher-ng/security.conf
+	# check for a free GID in the system group range (500-1000)
+	for GID in $$(seq 500 1000)
+	do
+		grep -q -e "^[^:]*:[^:]:$$GID:" /etc/group || break
+	done
+	[ $$GID -eq 1000 ] && { echo "ERROR: Could not find a suitable GID"; exit 1; }
 
-    # Basic setup information
-    echo -e "\033[1mapt-cacher-ng is now installed.\033[0m"
-    echo -e "Please follow the following instructions to enable it:"
-    echo -e "\t- Create the directory /srv/apt-cacher-ng on external storage"
-    echo -e "\t- If you're using extroot, it's as easy as:"
-    echo -e "\033[1m\t\t# mkdir -p /srv/apt-cacher-ng\033[0m"
-    echo -e "\t- If you're not using extroot, you can do something like this:"
-    echo -e "\033[1m\t\t# mkdir -p /mnt/sda1/srv/apt-cacher-ng\033[0m"
-    echo -e "\033[1m\t\t# mount -o bind /mnt/sda1/srv/apt-cacher-ng /srv/apt-cacher-ng\033[0m\n"
-    echo -e "\t- Once this step is complete, you can enable the \033[1mapt-cacher-ng\033[0m service by doing:"
-    echo -e "\033[1m\t\t# /etc/init.d/apt-cacher-ng enable\033[0m"
-    echo -e "\t- And you can start the service by doing:"
-    echo -e "\033[1m\t\t# /etc/init.d/apt-cacher-ng start \033[0m"
+	# add new group entry
+	cp /etc/group /etc/group.new
+	echo apt-cacher-ng:x:$$GID: >> /etc/group.new
+	mv /etc/group.new /etc/group
 
+	# add new user entry
+	cp /etc/passwd /etc/passwd.new
+	echo "apt-cacher-ng:!:$$UID:$$GID:apt-cacher-ng:/srv/apt-cacher-ng:/bin/ash" >> /etc/passwd.new
+	mv /etc/passwd.new /etc/passwd
+
+	# set file mode on security.conf
+	chown apt-cacher-ng:apt-cacher-ng /etc/apt-cacher-ng/security.conf
+	chmod 0600 /etc/apt-cacher-ng/security.conf
+
+	# TODO: Perhaps, in the future, we can come up with a better way to pick a Debian/Ubuntu mirror,
+	# perhaps via a lookup on the current IP address to determine country, or something.
+	# For now, we just use the generic mirrors, and they're copied from files/ to /etc/apt-cacher-ng/
+
+	# touch /etc/apt-cacher-ng/.configured to indicate that the package has been configured already
+	touch /etc/apt-cacher-ng/.configured
+
+	# Basic setup information
+	echo -e "\033[1m* apt-cacher-ng is now installed.\033[0m\n"
+	echo -e "Please follow the following instructions to enable it:"
+	echo -e "\t- Create the directory /srv/apt-cacher-ng on external storage"
+	echo -e "\t- If you're using extroot, it's as easy as:"
+	echo -e "\033[1m\t\t# mkdir -p /srv/apt-cacher-ng\033[0m"
+	echo -e "\t- If you're not using extroot, you can do something like this:"
+	echo -e "\033[1m\t\t# mkdir -p /mnt/sda1/srv/apt-cacher-ng\033[0m"
+	echo -e "\033[1m\t\t# mount -o bind /mnt/sda1/srv/apt-cacher-ng /srv/apt-cacher-ng\033[0m\n"
+	echo -e "\t- Once this step is complete, you can enable the \033[1mapt-cacher-ng\033[0m service by doing:"
+	echo -e "\033[1m\t\t# /etc/init.d/apt-cacher-ng enable\033[0m"
+	echo -e "\t- And you can start the service by doing:"
+	echo -e "\033[1m\t\t# /etc/init.d/apt-cacher-ng start \033[0m"
+	echo -e "\t- You can set your mirrors of choice in \033[1m/etc/apt-cacher-ng/backends_*\033[0m"
+	echo -e "\033[1m\t\t- It is recommended to leave /etc/apt-cacher-ng/*.default as-is.\033[0m"
+fi
 endef
 
 define Package/apt-cacher-ng/postrm
